# Generated by Django 3.0.2 on 2020-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200203_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hello'),
        ),
    ]
