# Generated by Django 2.2.4 on 2020-02-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_productpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpic',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Post'),
        ),
        migrations.AlterField(
            model_name='productpic',
            name='image',
            field=models.ImageField(upload_to='product_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productpic',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
