# Generated by Django 2.2.4 on 2020-02-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_travelpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='PFeaturedimage',
            field=models.ImageField(default='default.jpg', upload_to='PFeatured_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='PFeaturedimage2',
            field=models.ImageField(default='default.jpg', upload_to='PFeatured_pics2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='TFeaturedimage',
            field=models.ImageField(default='default.jpg', upload_to='TFeatured_pics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='TFeaturedimage2',
            field=models.ImageField(default='default.jpg', upload_to='TFeatured_pics2'),
        ),
    ]
