# Generated by Django 2.2.4 on 2020-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20200206_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PFeaturedimage',
            field=models.ImageField(default='Pdefault.jpg', upload_to='PFeatured_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PFeaturedimage2',
            field=models.ImageField(default='Pdefault.jpg', upload_to='PFeatured_pics2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TFeaturedimage',
            field=models.ImageField(default='Tdefault.jpg', upload_to='TFeatured_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='TFeaturedimage2',
            field=models.ImageField(default='Tdefault.jpg', upload_to='TFeatured_pics2'),
        ),
    ]
