# Generated by Django 2.2.4 on 2020-02-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_foodpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelpic',
            old_name='price',
            new_name='TravelExpenses',
        ),
    ]
